### ISSUE TITLE
Rewiew

### ISSUE THREAD

**Issue by OneScheer** [rempopo/CO34-op-aljaraniat-1A.takistan#1]
### Mission
- [x] Половина маркеров на русском, другая на английском. Либо всё на английском, либо IEDs и Cache перевести. 

### tSF
- [x] Authorization - не прописаны роли. Так и должно быть?
- [x] Брифинг - поддержка - написано про UH-1, но ничего не сказано про его вооружение. Может поставить Slick модификацию без вооружения?
- [x] Брифинг - поддержка - стоит указать, что такое артиллерийская система Альбудур. (По типу ```Артиллерийская система Альбудур - направляющая НАР на Toyota Hilux```). 
- [x] FARP - Рядом с FARP появляется Helipad. Выглядит не очень, особенно на склоне холма. Если вертолёт будет прилетать для дозаправка/ремонта, то садиться придётся на перекрёсток. Может перенести FARP ближе к заправке или на более плоское место.

### Gear
- [x] Может дать стрелкам и ещё кому-нибудь кроме сапёров лопаты? Лишними точно не будут, особенно в долине под огнём ДШК.
- [x] В китах нет ПНВ. Так задумано? Если да, то думаю стоит убрать возможность играть ночью. Или добавить побольше осветительных для ГП и сигнальные ракеты.

**Comment by 10Dozen** [comment]
Исправил в https://github.com/rempopo/CO34-op-aljaraniat-1A.takistan/commit/02e983ea21ae99c73fbd1d2beca751a9c94d7129

- Маркеры на русском
- UH-1H заменен на безоружный
- Добавлено описание РСЗО Альбудура
- Чуть сместил FARP
- Насыпал лопат и мешков для песка в ящик
